<?php

/**
 * Implements hook_requirements().
 */
function layout_discovery_requirements($phase) {
  $requirements = [];
  if ($phase === 'install') {
    if (\Drupal::moduleHandler()->moduleExists('layout_plugin')) {
      $requirements['nci_layout'] = [
        'description' => t('NCI Layouts cannot be installed because the Layout Plugin module is installed and incompatible.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }
  return $requirements;
}
